# Uncomment the next line to define a global platform for your project
platform :ios, '8.4'

target 'Harmony iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PeerTalk', :git => 'https://github.com/rsms/peertalk'
  pod 'MobileVLCKit'
  # Pods for Duet Desktop
end
